### ISSUE TITLE
Uncaught TypeError: Cannot read property 'accuracy' of undefined

### ISSUE THREAD

**Issue by cebe** [domoritz/leaflet-locatecontrol#80]
While debugging an other issue I constantly see this message popping up in the log:

Looks like self._event is not defined here: https://github.com/domoritz/leaflet-locatecontrol/blob/gh-pages/src/L.Control.Locate.js#L175

```
E/browser (14295): Console: Uncaught TypeError: Cannot read property 'accuracy' of undefined http://192.168.178.50/dev/cebe.cc/map/web/L.Control.Locate.js:175
```

**Comment by cebe** [comment]
The issue appears when the phone is not able to send a location because I am sitting indoor and GPS is not working.

**Comment by domoritz** [comment]
Can you show the stack trace for the error? This function should not be called, right? I don't think #81 is an appropriate fix since it just hides the problem.

**Comment by cebe** [comment]
I do not have a stack trace, it was not shown by the debugger. The problem occured when clicking the button multiple times before the timeout exceeded.

EDIT: I am able to reproduce it on firefox, ubuntu:

```
visualizeLocation()L.Cont...cate.js (Zeile 175)
stopFollowing()L.Cont...cate.js (Zeile 164)
stopLocate()L.Cont...cate.js (Zeile 285)
(?)()L.Cont...cate.js (Zeile 103)
handler()leaflet-src.js (Zeile 6402)
e = click clientX=24, clientY=117
```

**Comment by gmccrackin** [comment]
I have seen this too. Here is a stack trace from mine.

```
Uncaught TypeError: Cannot read property 'accuracy' of undefined
TypeError: Cannot read property 'accuracy' of undefined
    at visualizeLocation (/js/lib/L.Control.Locate.js:172:28)
    at stopFollowing (/js/lib/L.Control.Locate.js:161:13)
    at stopLocate (/js/lib/L.Control.Locate.js:300:17)
    at onLocationError (/js/lib/L.Control.Locate.js:320:13)
    at o.Mixin.Events.fireEvent (/js/lib/leaflet.js:6:5071)
    at o.Map.include._handleGeolocationError (/js/lib/leaflet.js:9:28025)
    at /js/lib/leaflet.js:6:513
```

I think the problem is in the onLocationError function myself.

Here are some of the UA's from this week that it has been a problem on.

```
Mozilla/5.0 (iPad; CPU OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D201
Mozilla/5.0 (iPad; CPU OS 7_1_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D201 Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_3 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B511 Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_6 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B651 Safari/9537.53
Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D167
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
```
