### ISSUE TITLE
NPM install

### ISSUE THREAD

**Issue by DrYSG** [domoritz/leaflet-locatecontrol#85]
I did not want to bother you. I found that that NPM can do direct installs from GIT. (Yes it is better to register it in the NPM registry, so that the version can be tracked. But, I did not want to trouble you).

BOWER is not working through our firewalls, and it much easier to combine node.js stuff if you use NPM. I can also customize the build.

Anyway, I can use the NPM url trick for this leaflet.minimap git repostory

```
npm install git+https://github.com/Norkart/Leaflet-MiniMap.git --save
```

However, when I try that with this repository I get the errors:

```
> npm install git://github.com/domoritz/leaflet-locatecontrol.git --save

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'git://github.com/domoritz/leaflet-locatecontrol.git',
1 verbose cli   '--save' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose readDependencies using package.json deps
6 verbose cache add [ 'git://github.com/domoritz/leaflet-locatecontrol.git', null ]
7 verbose cache add name=undefined spec="git://github.com/domoritz/leaflet-locatecontrol.git" args=["git://github.com/domoritz/leaflet-locatecontrol.git",null]
8 verbose parsed url { protocol: 'git:',
8 verbose parsed url   slashes: true,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: 'github.com',
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: 'github.com',
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: '/domoritz/leaflet-locatecontrol.git',
8 verbose parsed url   path: '/domoritz/leaflet-locatecontrol.git',
8 verbose parsed url   href: 'git://github.com/domoritz/leaflet-locatecontrol.git' }
9 silly lockFile d1e4cc4d-moritz-leaflet-locatecontrol-git git://github.com/domoritz/leaflet-locatecontrol.git
10 verbose lock git://github.com/domoritz/leaflet-locatecontrol.git C:\Users\ysg4206\AppData\Roaming\npm-cache\d1e4cc4d-moritz-leaflet-locatecontrol-git.lock
11 verbose addRemoteGit [ 'git://github.com/domoritz/leaflet-locatecontrol.git',
11 verbose addRemoteGit   'master' ]
12 verbose git clone git://github.com/domoritz/leaflet-locatecontrol.git Cloning into bare repository 'C:\Users\ysg4206\AppData\Roaming\npm-cache\_git-remotes\git-github-com-domoritz-leaflet-locatecontrol-git-d1e4cc4d'...
13 verbose git fetch -a origin (git://github.com/domoritz/leaflet-locatecontrol.git)
14 silly verifyOwnership skipping for windows
15 error Failed resolving git HEAD (git://github.com/domoritz/leaflet-locatecontrol.git) fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
15 error Failed resolving git HEAD (git://github.com/domoritz/leaflet-locatecontrol.git) Use '--' to separate paths from revisions, like this:
15 error Failed resolving git HEAD (git://github.com/domoritz/leaflet-locatecontrol.git) 'git <command> [<revision>...] -- [<file>...]'
16 silly lockFile d1e4cc4d-moritz-leaflet-locatecontrol-git git://github.com/domoritz/leaflet-locatecontrol.git
17 silly lockFile d1e4cc4d-moritz-leaflet-locatecontrol-git git://github.com/domoritz/leaflet-locatecontrol.git
18 error Error: Command failed: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
18 error Use '--' to separate paths from revisions, like this:
18 error 'git <command> [<revision>...] -- [<file>...]'
18 error
18 error     at ChildProcess.exithandler (child_process.js:648:15)
18 error     at ChildProcess.emit (events.js:98:17)
18 error     at maybeClose (child_process.js:756:16)
18 error     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
19 error If you need help, you may report this *entire* log,
19 error including the npm and node versions, at:
19 error     <http://github.com/npm/npm/issues>
20 error System Windows_NT 6.1.7601
21 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "git://github.com/domoritz/leaflet-locatecontrol.git" "--save"
22 error cwd G:\wwwroot\NodeToby
23 error node -v v0.10.30
24 error npm -v 1.4.21
25 error code 128
26 verbose exit [ 1, true ]

```

**Comment by domoritz** [comment]
Done in #5a8e768
